spring.application.name=Aethelgard-Archive-Core

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Swagger Settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
